name: leafcheck_project_v2
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=2.19.4 <3.0.0"

dependencies:
    camera: ^0.10.5+4
    camerawesome: ^1.4.0
    carousel_slider: ^4.2.1
    cloud_firestore: ^4.8.5
    cloud_functions: ^4.4.0
    csc_picker: ^0.2.7
    email_validator: ^2.1.17
    firebase_auth: ^4.9.0
    firebase_core: ^2.15.1
    fl_chart: ^0.62.0
    flutter:
        sdk: flutter
    flutter_launcher_icons: ^0.13.1
    flutter_native_splash: ^2.2.19
    flutter_spinkit: ^5.2.0
    gtext: ^0.0.3
    http: ^0.13.6
    image_picker: ^1.0.4
    intl: ^0.18.1
    path_provider: ^2.1.1
    percent_indicator: ^4.2.3
    provider: ^6.1.2
    shared_preferences: ^2.2.2
    simplytranslate: ^1.2.2
    tflite: ^1.1.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter_launcher_icons:
    android: true
    image_path: "assets/logos/leafcheck-icon.png"
    adaptive_icon_background: "#ffffff"
    adaptive-icon_foreground: "assets/logos/1024.png"
    min_sdk_android: 21

flutter_native_splash:
    color: "#ffffff"
    background_image: "assets/logos/leafcheck-logo.png"
    image: assets/logos/leafcheck-icon.png

    android_12:
        color: "#ffffff"
        image: assets/logos/leafcheck-logo.png

flutter:
    uses-material-design: true
    assets:
        - assets/logos/
        - assets/home/
        - assets/tflite_model/labels.txt
        - assets/tflite_model/tf_lite_model.tflite
        - assets/leaf_not/labels.txt
        - assets/leaf_not/tf_lite_model.tflite
